PREFIX x: <http://ifs.tuwien.ac.at/tulid/group16#>

CONSTRUCT {?subj ?p ?o. ?sc x:semester ?sem. }
WHERE {
  ?subj a x:Course.
  ?subj x:hasID ?id
  OPTIONAL{
  	?subj ?p ?o
  }
  OPTIONAL{
  	?subj x:semesterCourses ?sc.
  	?sc x:semester ?sem
  }
  FILTER(?id = ?paramId)
}